### ISSUE TITLE
i3 config changer

### ISSUE THREAD

**Issue by Dobbie03** [ARCHLabs/Archlabs-User-Home#33]
See here, this could be worth intergrating into i3 for +6

**Comment by Dobbie03** [comment]
Still would like to see this included.

**Comment by Dobbie03** [comment]
This time with the link

https://www.reddit.com/r/unixporn/comments/6srj0g/i3gaps_config_changer_ive_been_working_on/

**Comment by natemaia** [comment]
I can set it all up and what not but it's not without quirks
The slightest change between the config and the template that it uses will result in themes not switching
so it's more user specific (you'll be editing double files otherwise)

It took me a long ass time to figure it out as his documentation isn't the greatest
I can go into the details if you'd like but the point is, it's alot easier to have your configs setup the way you want before you start using this. Once you've got this good then you track them with the config switcher, it copies them to a yaml template, you then edit with some yaml code which is replaced with values (colour, text, whatever). stored in your group/theme < whatever you named them 
themename.yaml file holds all the values which will be read when loading a theme.

The actual dropdown is a whole different program that reads..you guessed it another yaml file :D
and makes a nice little dropdown menu with the values stores there.. luckily it can auto dump this from the file found in a given group/theme

It can be made to do just about anything in a text file and set the values
(like setting the wallpaper terminal colors etc)
So in theory an openbox theme could be made to be switchable... ;) ;) nudge nudge
